Repository nowsprinting/test-helper, pull requests merged in 2024-08, with the labels that each got.

#91 fix: Convert Path.GetFullPath(..) return values to Unix-style separators
  RuntimeInternals/SceneManagerHelper.cs
Labels: bug

#92 Pin test-framework version to v1.4.4
  .github/workflows/test.yml
  Makefile
Labels: chore

#95 Fix for Unity 2019
  RuntimeInternals/SceneManagerHelper.cs
Labels: bug

#94 Scene path inference for LoadSceneAttribute & BuildSceneAttribute
  Runtime/Attributes/BuildSceneAttribute.cs
  Runtime/Attributes/LoadSceneAttribute.cs
  Tests/Runtime/Attributes/BuildSceneAttributeTest.cs
  Tests/Runtime/Attributes/BuildSceneAttributeTest.unity
  Tests/Runtime/Attributes/BuildSceneAttributeTest.unity.meta
  Tests/Runtime/Attributes/LoadSceneAttributeTest.cs
  Tests/Runtime/Attributes/LoadSceneAttributeTest.unity
  Tests/Runtime/Attributes/LoadSceneAttributeTest.unity.meta
Labels: enhancement
